version: '3.8'

services:

  appointment:
    build: ./services/appointment
    ports:
      - "5001:5001"
    networks:
      - healthcare-network

  gateway:
    build: ./services/gateway
    ports:
      - "5002:5002"
    networks:
      - healthcare-network

  patient:
    build: ./services/patient
    ports:
      - "5003:5003"
    networks:
      - healthcare-network

  billing:
    build: ./services/billing
    ports:
      - "5004:5004"
    networks:
      - healthcare-network

  prescription:
    build: ./services/prescription
    ports:
      - "5005:5005"
    networks:
      - healthcare-network

networks:
  healthcare-network:
    driver: bridge
